from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

from .keywords import Category
from .parser import parse
from .splitter import SplitResult, SplitSelection, _sha256, compute_split, split_with_includes

_MANIFEST_DIR = ".filefold"
_MANIFEST_FILE = "workspace.json"


# ---------------------------------------------------------------------------
# Manifest records
# ---------------------------------------------------------------------------

@dataclass
class FileRecord:
    """Hash of a workspace file at the time it was last generated by FileFold."""
    sha256: str
    role: str            # "mother" | "child"
    category: str | None = None


# ---------------------------------------------------------------------------
# Reimport status
# ---------------------------------------------------------------------------

@dataclass
class ChildStatus:
    filename: str
    category: Category
    changed_in_new_mother: bool  # new content differs from last split
    manually_edited: bool        # file on disk was changed after last split
    new_content: str             # what would be written if regenerated


@dataclass
class ReimportPreview:
    """Result of analysing a new mother file against the current workspace state."""
    new_mother_content: str
    statuses: list[ChildStatus]

    @property
    def safe_to_update(self) -> list[ChildStatus]:
        """Changed in new mother, NOT manually edited — safe to overwrite."""
        return [s for s in self.statuses if s.changed_in_new_mother and not s.manually_edited]

    @property
    def needs_attention(self) -> list[ChildStatus]:
        """Changed in new mother AND manually edited — engineer must decide."""
        return [s for s in self.statuses if s.changed_in_new_mother and s.manually_edited]

    @property
    def unchanged(self) -> list[ChildStatus]:
        """No change in new mother — nothing to do."""
        return [s for s in self.statuses if not s.changed_in_new_mother]


# ---------------------------------------------------------------------------
# Workspace
# ---------------------------------------------------------------------------

@dataclass
class Workspace:
    path: Path
    name: str
    source_name: str
    selections: list[SplitSelection]
    file_records: dict[str, FileRecord] = field(default_factory=dict)
    created_at: str = ""
    updated_at: str = ""

    @property
    def manifest_path(self) -> Path:
        return self.path / _MANIFEST_DIR / _MANIFEST_FILE

    # ------------------------------------------------------------------
    # Persistence
    # ------------------------------------------------------------------

    def _save(self) -> None:
        self.updated_at = datetime.now(timezone.utc).isoformat()
        manifest_dir = self.path / _MANIFEST_DIR
        manifest_dir.mkdir(exist_ok=True)
        data = {
            "name": self.name,
            "source_name": self.source_name,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
            "selections": [
                {"category": s.category.value, "filename": s.filename}
                for s in self.selections
            ],
            "file_records": {
                name: {"sha256": r.sha256, "role": r.role, "category": r.category}
                for name, r in self.file_records.items()
            },
        }
        self.manifest_path.write_text(json.dumps(data, indent=2), encoding="utf-8")

    # ------------------------------------------------------------------
    # Constructors
    # ------------------------------------------------------------------

    @classmethod
    def create(
        cls,
        directory: Path,
        source: Path,
        selections: list[SplitSelection],
    ) -> Workspace:
        """Create a new workspace, run initial split, write manifest."""
        directory.mkdir(parents=True, exist_ok=True)
        blocks = parse(source)
        result = split_with_includes(blocks, source, directory, selections)

        now = datetime.now(timezone.utc).isoformat()
        ws = cls(
            path=directory,
            name=directory.name,
            source_name=source.name,
            selections=selections,
            created_at=now,
            updated_at=now,
        )
        ws._record_result(result)
        ws._save()
        return ws

    @classmethod
    def load(cls, directory: Path) -> Workspace:
        """Load an existing workspace from its manifest."""
        manifest = directory / _MANIFEST_DIR / _MANIFEST_FILE
        if not manifest.exists():
            raise FileNotFoundError(f"No FileFold workspace at {directory}")
        data = json.loads(manifest.read_text(encoding="utf-8"))
        return cls(
            path=directory,
            name=data["name"],
            source_name=data["source_name"],
            selections=[
                SplitSelection(Category(s["category"]), s["filename"])
                for s in data["selections"]
            ],
            file_records={
                name: FileRecord(**r) for name, r in data["file_records"].items()
            },
            created_at=data["created_at"],
            updated_at=data["updated_at"],
        )

    # ------------------------------------------------------------------
    # Re-import
    # ------------------------------------------------------------------

    def reimport_preview(self, new_source: Path) -> ReimportPreview:
        """Analyse a new mother file: compute what changed without writing anything."""
        blocks = parse(new_source)
        new_mother_content, new_child_contents = compute_split(blocks, self.selections)

        sel_map = {s.filename: s for s in self.selections}
        statuses: list[ChildStatus] = []

        for filename, sel in sel_map.items():
            new_content = new_child_contents.get(filename, "")
            new_hash = _sha256(new_content)
            last_hash = self.file_records.get(filename, FileRecord("", "child")).sha256

            current_path = self.path / filename
            if current_path.exists():
                current_hash = _sha256(
                    current_path.read_text(encoding="utf-8", errors="surrogateescape")
                )
            else:
                current_hash = ""

            statuses.append(ChildStatus(
                filename=filename,
                category=sel.category,
                changed_in_new_mother=(new_hash != last_hash),
                manually_edited=(bool(last_hash) and current_hash != last_hash),
                new_content=new_content,
            ))

        return ReimportPreview(new_mother_content=new_mother_content, statuses=statuses)

    def reimport_apply(
        self,
        new_source: Path,
        preview: ReimportPreview,
        filenames_to_update: set[str],
    ) -> None:
        """Write approved child updates and the new mother file."""
        for status in preview.statuses:
            if status.filename in filenames_to_update and status.new_content:
                child_path = self.path / status.filename
                child_path.write_text(
                    status.new_content, encoding="utf-8", errors="surrogateescape"
                )
                self.file_records[status.filename] = FileRecord(
                    sha256=_sha256(status.new_content),
                    role="child",
                    category=status.category.value,
                )

        mother_path = self.path / self.source_name
        mother_path.write_text(
            preview.new_mother_content, encoding="utf-8", errors="surrogateescape"
        )
        self.file_records[self.source_name] = FileRecord(
            sha256=_sha256(preview.new_mother_content), role="mother"
        )
        self._save()

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _record_result(self, result: SplitResult) -> None:
        self.file_records[result.mother_path.name] = FileRecord(
            sha256=result.mother_sha256, role="mother"
        )
        for child in result.children:
            self.file_records[child.filename] = FileRecord(
                sha256=child.sha256, role="child", category=child.category.value
            )
