from __future__ import annotations

import json
import re as _re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

from .keywords import Category
from .parser import parse
from .splitter import SplitResult, SplitSelection, SubSplitSelection, _sha256, compute_split, split_with_includes

_MANIFEST_DIR = ".filefold"
_MANIFEST_FILE = "workspace.json"


# ---------------------------------------------------------------------------
# Manifest records
# ---------------------------------------------------------------------------

@dataclass
class FileRecord:
    """Hash of a workspace file at the time it was last generated by FileFold."""
    sha256: str
    role: str                  # "mother" | "child" | "grandchild"
    category: str | None = None
    parent: str | None = None  # parent child filename for grandchildren


# ---------------------------------------------------------------------------
# Reimport status
# ---------------------------------------------------------------------------

@dataclass
class ChildStatus:
    filename: str
    category: Category
    changed_in_new_mother: bool  # new content differs from last split
    manually_edited: bool        # file on disk was changed after last split
    new_content: str             # what would be written if regenerated


@dataclass
class ReimportPreview:
    """Result of analysing a new mother file against the current workspace state."""
    new_mother_content: str
    statuses: list[ChildStatus]

    @property
    def safe_to_update(self) -> list[ChildStatus]:
        """Changed in new mother, NOT manually edited — safe to overwrite."""
        return [s for s in self.statuses if s.changed_in_new_mother and not s.manually_edited]

    @property
    def needs_attention(self) -> list[ChildStatus]:
        """Changed in new mother AND manually edited — engineer must decide."""
        return [s for s in self.statuses if s.changed_in_new_mother and s.manually_edited]

    @property
    def unchanged(self) -> list[ChildStatus]:
        """No change in new mother — nothing to do."""
        return [s for s in self.statuses if not s.changed_in_new_mother]


# ---------------------------------------------------------------------------
# Workspace
# ---------------------------------------------------------------------------

@dataclass
class Workspace:
    path: Path
    name: str
    source_name: str
    selections: list[SplitSelection]
    file_records: dict[str, FileRecord] = field(default_factory=dict)
    created_at: str = ""
    updated_at: str = ""

    @property
    def manifest_path(self) -> Path:
        return self.path / _MANIFEST_DIR / _MANIFEST_FILE

    # ------------------------------------------------------------------
    # Persistence
    # ------------------------------------------------------------------

    def _save(self) -> None:
        self.updated_at = datetime.now(timezone.utc).isoformat()
        manifest_dir = self.path / _MANIFEST_DIR
        manifest_dir.mkdir(exist_ok=True)
        data = {
            "name": self.name,
            "source_name": self.source_name,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
            "selections": [
                {
                    "category": s.category.value,
                    "filename": s.filename,
                    "sub_selections": [
                        {"sub_category": ss.sub_category, "filename": ss.filename}
                        for ss in s.sub_selections
                    ],
                }
                for s in self.selections
            ],
            "file_records": {
                name: {
                    "sha256": r.sha256,
                    "role": r.role,
                    "category": r.category,
                    "parent": r.parent,
                }
                for name, r in self.file_records.items()
            },
        }
        self.manifest_path.write_text(json.dumps(data, indent=2), encoding="utf-8")

    # ------------------------------------------------------------------
    # Constructors
    # ------------------------------------------------------------------

    @classmethod
    def create(
        cls,
        directory: Path,
        source: Path,
        selections: list[SplitSelection],
    ) -> Workspace:
        """Create a new workspace, run initial split, write manifest."""
        directory.mkdir(parents=True, exist_ok=True)
        blocks = parse(source)
        result = split_with_includes(blocks, source, directory, selections)

        now = datetime.now(timezone.utc).isoformat()
        ws = cls(
            path=directory,
            name=directory.name,
            source_name=source.name,
            selections=selections,
            created_at=now,
            updated_at=now,
        )
        ws._record_result(result)
        ws._save()
        return ws

    @classmethod
    def load(cls, directory: Path) -> Workspace:
        """Load an existing workspace from its manifest."""
        manifest = directory / _MANIFEST_DIR / _MANIFEST_FILE
        if not manifest.exists():
            raise FileNotFoundError(f"No FileFold workspace at {directory}")
        data = json.loads(manifest.read_text(encoding="utf-8"))
        return cls(
            path=directory,
            name=data["name"],
            source_name=data["source_name"],
            selections=[
                SplitSelection(
                    Category(s["category"]),
                    s["filename"],
                    sub_selections=[
                        SubSplitSelection(ss["sub_category"], ss["filename"])
                        for ss in s.get("sub_selections", [])
                    ],
                )
                for s in data["selections"]
            ],
            file_records={
                name: FileRecord(
                    sha256=r["sha256"],
                    role=r["role"],
                    category=r.get("category"),
                    parent=r.get("parent"),
                )
                for name, r in data["file_records"].items()
            },
            created_at=data["created_at"],
            updated_at=data["updated_at"],
        )

    # ------------------------------------------------------------------
    # Re-import
    # ------------------------------------------------------------------

    def reimport_preview(self, new_source: Path) -> ReimportPreview:
        """Analyse a new mother file: compute what changed without writing anything."""
        blocks = parse(new_source)
        new_mother_content, new_child_contents = compute_split(blocks, self.selections)

        # Build flat list of all tracked files: children + sub-children
        all_files: list[tuple[str, Category]] = []
        for sel in self.selections:
            all_files.append((sel.filename, sel.category))
            for ss in sel.sub_selections:
                all_files.append((ss.filename, sel.category))

        statuses: list[ChildStatus] = []
        for filename, category in all_files:
            new_content = new_child_contents.get(filename, "")
            new_hash = _sha256(new_content)
            last_hash = self.file_records.get(filename, FileRecord("", "child")).sha256

            current_path = self.path / filename
            current_hash = (
                _sha256(current_path.read_text(encoding="utf-8", errors="surrogateescape"))
                if current_path.exists() else ""
            )

            statuses.append(ChildStatus(
                filename=filename,
                category=category,
                changed_in_new_mother=(new_hash != last_hash),
                manually_edited=(bool(last_hash) and current_hash != last_hash),
                new_content=new_content,
            ))

        return ReimportPreview(new_mother_content=new_mother_content, statuses=statuses)

    def reimport_apply(
        self,
        new_source: Path,
        preview: ReimportPreview,
        filenames_to_update: set[str],
        added_selections: list[SplitSelection] | None = None,
    ) -> None:
        """Write approved child updates, optional new selections, and the new mother file."""
        all_selections = list(self.selections)
        truly_new: list[SplitSelection] = []

        if added_selections:
            existing_cats = {s.category for s in self.selections}
            truly_new = [s for s in added_selections if s.category not in existing_cats]
            all_selections.extend(truly_new)

        # Recompute full split when new selections are added (updates *INCLUDE lines in mother)
        if truly_new:
            blocks = parse(new_source)
            new_mother_content, new_child_contents = compute_split(blocks, all_selections)
        else:
            new_mother_content = preview.new_mother_content
            new_child_contents = {s.filename: s.new_content for s in preview.statuses}

        # preview.statuses flattens children and sub-children into one list, so the
        # role/parent of each file has to come from the selections, not the status.
        # Recording everything as a parentless "child" is what un-nests sub-children
        # and makes them resurface as top-level children after a reimport.
        roles: dict[str, tuple[str, str | None]] = {}
        for sel in all_selections:
            roles[sel.filename] = ("child", None)
            for ss in sel.sub_selections:
                roles[ss.filename] = ("grandchild", sel.filename)

        # Write existing children that were approved
        for status in preview.statuses:
            if status.filename in filenames_to_update:
                content = new_child_contents.get(status.filename, status.new_content)
                if content:
                    (self.path / status.filename).write_text(
                        content, encoding="utf-8", errors="surrogateescape"
                    )
                    role, parent = roles.get(status.filename, ("child", None))
                    self.file_records[status.filename] = FileRecord(
                        sha256=_sha256(content),
                        role=role,
                        category=status.category.value,
                        parent=parent,
                    )

        # Write newly added children
        for sel in truly_new:
            content = new_child_contents.get(sel.filename, "")
            if content:
                (self.path / sel.filename).write_text(
                    content, encoding="utf-8", errors="surrogateescape"
                )
                self.file_records[sel.filename] = FileRecord(
                    sha256=_sha256(content), role="child", category=sel.category.value
                )

        if truly_new:
            self.selections = all_selections

        # Always write the new mother using the uploaded filename
        new_name = new_source.name
        (self.path / new_name).write_text(
            new_mother_content, encoding="utf-8", errors="surrogateescape"
        )

        # Clean up old mother file when the filename changed
        if new_name != self.source_name:
            old = self.path / self.source_name
            if old.exists():
                old.unlink()
            self.file_records.pop(self.source_name, None)
            self.source_name = new_name

        self.file_records[new_name] = FileRecord(
            sha256=_sha256(new_mother_content), role="mother"
        )
        self._save()

    # ------------------------------------------------------------------
    # Recombine
    # ------------------------------------------------------------------

    def recombine(self, filenames: list[str]) -> None:
        """Fold listed child/sub-child files back into their parent file.

        For each filename:
        - Expand its content (recursively inlining any sub-includes it holds).
        - Replace the *INCLUDE line in the parent with that expanded content.
        - Delete the file and any files it owned.
        - Remove it from selections/sub_selections and file_records.
        """
        def _expand(path: Path) -> str:
            """Return content with all *INCLUDE lines replaced recursively."""
            text = path.read_text(encoding="utf-8", errors="surrogateescape")
            def _sub(m: _re.Match) -> str:
                inc = self.path / m.group(1).strip()
                return _expand(inc) if inc.exists() else m.group(0)
            return _re.sub(
                r"^\*INCLUDE\s*,\s*INPUT\s*=\s*(.+?)\s*$",
                _sub, text, flags=_re.IGNORECASE | _re.MULTILINE,
            )

        def _sub_files(fname: str) -> list[str]:
            """Return fname plus all files whose parent is fname (recursively)."""
            result = [fname]
            for n, r in self.file_records.items():
                if r.parent == fname:
                    result.extend(_sub_files(n))
            return result

        for fname in filenames:
            rec = self.file_records.get(fname)
            if not rec:
                continue

            parent_fname = rec.parent if rec.role == "grandchild" else self.source_name
            parent_path  = self.path / parent_fname
            child_path   = self.path / fname

            if not child_path.exists():
                continue

            # Expand and inline
            expanded = _expand(child_path).rstrip("\n")
            parent_text = parent_path.read_text(encoding="utf-8", errors="surrogateescape")
            pattern = _re.compile(
                r"^\*INCLUDE\s*,\s*INPUT\s*=\s*" + _re.escape(fname) + r"[ \t]*$",
                _re.IGNORECASE | _re.MULTILINE,
            )
            new_parent = pattern.sub(expanded, parent_text, count=1)
            parent_path.write_text(new_parent, encoding="utf-8", errors="surrogateescape")

            # Update parent hash
            parent_rec = self.file_records[parent_fname]
            self.file_records[parent_fname] = FileRecord(
                sha256=_sha256(new_parent),
                role=parent_rec.role,
                category=parent_rec.category,
                parent=parent_rec.parent,
            )

            # Delete this file and all files it owns
            for to_del in _sub_files(fname):
                p = self.path / to_del
                if p.exists():
                    p.unlink()
                self.file_records.pop(to_del, None)

            # Update selections
            if rec.role == "child":
                self.selections = [s for s in self.selections if s.filename != fname]
            elif rec.role == "grandchild":
                for sel in self.selections:
                    sel.sub_selections = [ss for ss in sel.sub_selections if ss.filename != fname]

        self._save()

    # ------------------------------------------------------------------
    # Resplit child
    # ------------------------------------------------------------------

    def resplit_child(self, category_str: str, new_sub: list[SubSplitSelection]) -> None:
        """Modify sub-splits for an already-extracted category.

        Steps:
        1. Fold any existing sub-split files back into the child (recombine).
        2. Re-parse the now-clean child file and extract the desired sub-splits.
        """
        existing_sel = next((s for s in self.selections if s.category.value == category_str), None)
        if not existing_sel:
            raise ValueError(f"Category '{category_str}' is not yet extracted")

        # Recombine only the sub-splits that actually exist on disk
        to_fold = [ss.filename for ss in existing_sel.sub_selections
                   if (self.path / ss.filename).exists()]
        if to_fold:
            self.recombine(to_fold)
            # recombine clears existing_sel.sub_selections and saves; re-find the selection
            existing_sel = next((s for s in self.selections if s.category.value == category_str), None)

        child_path = self.path / existing_sel.filename
        if not child_path.exists():
            raise FileNotFoundError(f"Child file '{existing_sel.filename}' not found")

        if new_sub:
            temp_sel = SplitSelection(existing_sel.category, existing_sel.filename, list(new_sub))
            blocks = parse(child_path)
            _, child_contents = compute_split(blocks, [temp_sel])

            # child_contents maps filename -> content for every file that was produced.
            # The parent child file (existing_sel.filename) is always present; the sub-split
            # files only appear when matching keyword blocks were actually found.
            requested_sub_files = {ss.filename for ss in new_sub}
            created_sub_files = {f for f in child_contents if f in requested_sub_files}

            if not created_sub_files:
                raise ValueError(
                    f"No sub-split blocks found in '{existing_sel.filename}'. "
                    f"The file may use nested *PART containers or lack the expected keywords."
                )

            for filename, content in child_contents.items():
                (self.path / filename).write_text(content, encoding="utf-8", errors="surrogateescape")

            # Only record sub-selections that were actually written to disk
            existing_sel.sub_selections = [ss for ss in new_sub if ss.filename in created_sub_files]

            for filename, content in child_contents.items():
                sha = _sha256(content)
                if filename == existing_sel.filename:
                    old_rec = self.file_records.get(filename)
                    self.file_records[filename] = FileRecord(
                        sha256=sha,
                        role=old_rec.role if old_rec else "child",
                        category=old_rec.category if old_rec else category_str,
                        parent=old_rec.parent if old_rec else None,
                    )
                else:
                    self.file_records[filename] = FileRecord(
                        sha256=sha,
                        role="grandchild",
                        category=category_str,
                        parent=existing_sel.filename,
                    )

        self._save()

    # ------------------------------------------------------------------
    # Rename child / grandchild
    # ------------------------------------------------------------------

    def rename_child(self, old_filename: str, new_filename: str) -> None:
        """Rename a child or grandchild file in-place.

        - Moves the file on disk.
        - Updates the *INCLUDE line in the parent file.
        - Updates selections, sub_selections, and file_records in the manifest.
        """
        rec = self.file_records.get(old_filename)
        if not rec:
            raise ValueError(f"File '{old_filename}' is not tracked in this workspace")

        old_path = self.path / old_filename
        new_path = self.path / new_filename

        if not old_path.exists():
            raise FileNotFoundError(f"File '{old_filename}' not found on disk")
        if new_path.exists():
            raise ValueError(f"Target filename '{new_filename}' already exists")

        # Move the file
        old_path.rename(new_path)

        # Update the *INCLUDE line in the parent file. The mother has no parent to
        # update — it is instead referenced by source_name, handled below.
        parent_fname = rec.parent if rec.role == "grandchild" else self.source_name
        parent_path = self.path / parent_fname
        if rec.role != "mother" and parent_path.exists():
            parent_text = parent_path.read_text(encoding="utf-8", errors="surrogateescape")
            parent_text = _re.sub(
                r"(?i)(\*INCLUDE\s*,\s*INPUT\s*=\s*)" + _re.escape(old_filename) + r"([ \t]*)$",
                lambda m: m.group(1) + new_filename + m.group(2),
                parent_text,
                flags=_re.MULTILINE,
            )
            parent_path.write_text(parent_text, encoding="utf-8", errors="surrogateescape")

        # Update file_records
        self.file_records.pop(old_filename)
        self.file_records[new_filename] = FileRecord(
            sha256=rec.sha256,
            role=rec.role,
            category=rec.category,
            parent=rec.parent,
        )

        # Update any grandchildren that reference old_filename as their parent
        if rec.role == "child":
            for r in self.file_records.values():
                if r.parent == old_filename:
                    r.parent = new_filename

        # The mother is tracked by source_name, not by a selection. Leaving it stale
        # points the workspace at a filename that no longer exists on disk.
        if rec.role == "mother":
            self.source_name = new_filename

        # Update selections / sub_selections
        if rec.role == "child":
            for sel in self.selections:
                if sel.filename == old_filename:
                    sel.filename = new_filename
        elif rec.role == "grandchild":
            for sel in self.selections:
                for ss in sel.sub_selections:
                    if ss.filename == old_filename:
                        ss.filename = new_filename

        self._save()

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _record_result(self, result: SplitResult) -> None:
        self.file_records[result.mother_path.name] = FileRecord(
            sha256=result.mother_sha256, role="mother"
        )
        for child in result.children:
            role = "grandchild" if child.parent else "child"
            self.file_records[child.filename] = FileRecord(
                sha256=child.sha256,
                role=role,
                category=child.category.value if child.category else None,
                parent=child.parent,
            )
