#!/usr/bin/env python3
"""Extract keyword facts from the Abaqus Keywords Reference Guide into a Python module.

The Reference has one HTML page per keyword (chNNabkMM.html). This script reads a local
copy of those pages and writes src/filefold/core/keyword_reference.py, a table of facts
only (name, data type, level, documented parent keywords). No documentation text is
copied; the pages themselves are not part of this repository.

    python scripts/extract_keyword_reference.py --html-dir /path/to/pages

Facts per keyword:
  types    "model" and/or "history"  (the page's "Type:" line)
  levels   subset of model, step, part, part instance, assembly  (the "Level:" line)
  parents  keywords the page says it must be used with / within (e.g. *ELASTIC -> *MATERIAL),
           taken from sentences like "must be used in conjunction with the *X option".
           Prose-derived, so treat as strong hints; keywords.py reviews how they are used.
"""
from __future__ import annotations

import argparse
import glob
import html
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "filefold" / "core" / "keyword_reference.py"
SOURCE = "Abaqus 2016 Keywords Reference Guide"

_KW = re.compile(r"\*[A-Z][A-Z0-9\-/]*(?: [A-Z][A-Z0-9\-/]*)*")
_PARENT_PHRASE = re.compile(
    r"((?:must|can|may|should)\s+(?:only\s+)?be\s+used\s+(?:only\s+)?(?:in\s+conjunction\s+)?with"
    r"|must\s+appear\s+within|must\s+immediately\s+follow|can\s+be\s+used\s+only\s+as\s+part\s+of"
    r"|is\s+used\s+only\s+in\s+conjunction\s+with|used\s+only\s+with)",
    re.I,
)


def _norm(name: str) -> str:
    return " ".join(name.lstrip("*").upper().split())


def _lines(page: str) -> list[str]:
    body = page[page.find("<body"):]
    body = re.sub(r"<script.*?</script>", "", body, flags=re.S)
    body = html.unescape(re.sub(r"<[^>]+>", "\n", body))
    return [l.strip() for l in body.splitlines() if l.strip()]


def _after(lines: list[str], label: str) -> str:
    if label not in lines:
        return ""
    i = lines.index(label) + 1
    out = []
    while i < len(lines) and not lines[i].endswith(":") and lines[i] != "Reference:":
        out.append(lines[i])
        i += 1
    return " ".join(out)


def _types(text: str) -> tuple[str, ...]:
    t = text.lower()
    found = [k for k in ("model", "history") if k in t]
    return tuple(found)


def _levels(text: str) -> tuple[str, ...]:
    t = text.lower()
    # "Part instance" must not also count as "part"
    flat = t.replace("part instance", "\0")
    found = []
    for label, probe in (("model", "model"), ("step", "step"), ("part", "part"),
                         ("part instance", "\0"), ("assembly", "assembly")):
        if probe in flat:
            found.append(label)
    return tuple(found)


def extract(html_dir: Path) -> dict[str, tuple[tuple[str, ...], tuple[str, ...], tuple[str, ...]]]:
    raw: dict[str, tuple[tuple, tuple, list[str]]] = {}
    for path in sorted(glob.glob(str(html_dir / "ch*abk*.html"))):
        page = Path(path).read_text(encoding="utf-8", errors="replace")
        m = re.search(r"<title>(.*?)</title>", page, flags=re.S)
        if not m or not m.group(1).strip().startswith("*"):
            continue
        name = _norm(m.group(1))
        lines = _lines(page)
        text = " ".join(lines)
        intro = text[: text.find(" Products:")] if " Products:" in text else text[:600]
        parents: list[str] = []
        for phrase in _PARENT_PHRASE.finditer(intro):
            sentence = re.split(r"\.\s", intro[phrase.start(): phrase.end() + 160])[0]
            parents += [_norm(k) for k in _KW.findall(sentence)]
        raw[name] = (_types(_after(lines, "Type:")), _levels(_after(lines, "Level:")), parents)

    facts = {}
    for name, (types, levels, parents) in raw.items():
        # keep only parents that are real keywords with a page (drops typos such as FRAME SECTIO)
        keep = tuple(sorted({p for p in parents if p in raw and p != name}))
        facts[name] = (types, levels, keep)
    return facts


def write(facts: dict, out: Path = OUT) -> None:
    lines = [
        f'"""Keyword facts from the {SOURCE}. GENERATED by scripts/extract_keyword_reference.py.',
        "",
        "Do not edit by hand. FACTS maps a keyword name (uppercase, no asterisk) to",
        "(types, levels, parents): where it may appear and which keywords it belongs with.",
        "Only facts are stored, no documentation text.",
        '"""',
        "from __future__ import annotations",
        "",
        f'SOURCE = "{SOURCE}"',
        "",
        "FACTS: dict[str, tuple[tuple[str, ...], tuple[str, ...], tuple[str, ...]]] = {",
    ]
    for name in sorted(facts):
        types, levels, parents = facts[name]
        lines.append(f"    {name!r}: ({types!r}, {levels!r}, {parents!r}),")
    lines.append("}")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--html-dir", type=Path, required=True)
    ap.add_argument("--out", type=Path, default=OUT)
    args = ap.parse_args()
    facts = extract(args.html_dir)
    write(facts, args.out)
    with_parent = sum(1 for f in facts.values() if f[2])
    print(f"wrote {args.out} ({len(facts)} keywords, {with_parent} with a documented parent)")


if __name__ == "__main__":
    main()
